# Generated by Django 2.2.5 on 2019-09-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='pictures')),
                ('res', models.ImageField(blank=True, upload_to='')),
                ('timestamp', models.TextField()),
            ],
            options={
                'db_table': 'picture',
            },
        ),
    ]
