# Generated by Django 2.2.4 on 2019-09-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190907_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='classification152',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pic',
            name='classification18',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pic',
            name='transfer',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
